### ISSUE TITLE
cant work hook_art

### ISSUE THREAD

**Issue by wengxianxun** [lasting-yang/hook_art#10]
wxxdeMacBook-Pro:frida_hook_libart-master wxx$ frida -U -f com.xingin.xhs -l hook_art.js
     ____
    / _  |   Frida 15.1.23 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to ONEPLUS A3010 (id=f3f66c2c)
Failed to spawn: command failed: 99

**Comment by lasting-yang** [comment]
小红书检测frida

**Comment by lasting-yang** [comment]
![WX20220601-102421](https://user-images.githubusercontent.com/13957779/171315372-7d904d07-2c22-41e0-a725-8112d523ac1f.png)

不要使用模拟器，可以Spawning注入小红书，几秒后，小红书检测到frida回自动闪退

**Comment by wengxianxun** [comment]
可以了，我手机里的fridaserver环境出现问题，重新弄一遍就行了
