### ISSUE TITLE
大佬们，那个hook出来的 fnOffset: 0xbc6b4 就是函数的偏移地址吗

### ISSUE THREAD

**Issue by wengxianxun** [lasting-yang/hook_art#11]
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/831898/172563541-7d090fe7-284d-4f52-aac2-2fb816711b01.png">

**Comment by lasting-yang** [comment]
fnOffset是基于模块的偏移，刚刚更新了代码，可以看到模块和偏移
