### ISSUE TITLE
对于动态加载的so，无法找到模块

### ISSUE THREAD

**Issue by Ezreal147** [lasting-yang/hook_art#4]
360加固自己实现了类似linker的so加载，这样加载出来的so无法被被识别为module，find_module为null

**Comment by JJymsWorld** [comment]
> 360加固自己实现了类似linker的so加载，这样加载出来的so无法被被识别为module，find_module为null

想问一下大佬您解决了吗这个问题 能否赐教一下

**Comment by thouger** [comment]
遇到一样的问题

**Comment by JJymsWorld** [comment]
> 遇到一样的问题

别用模拟器用真机试试

**Comment by thouger** [comment]
> > 遇到一样的问题
> 
> 别用模拟器用真机试试

感谢回复！
