### ISSUE TITLE
您好，麻烦问个问题。我在使用 frida -U --no-pause -f com.xingin.xhs -l ./hook_art.js 命令后 app会启动，但是模拟器会重启，用的是逍遥模拟器。

### ISSUE THREAD

**Issue by xueleilei120** [lasting-yang/hook_art#6]
我截个图，麻烦帮忙看下，多谢。
![图片](https://user-images.githubusercontent.com/18748511/109782597-034e1000-7c44-11eb-90aa-496e503c8e43.png)

**Comment by xueleilei120** [comment]
![图片](https://user-images.githubusercontent.com/18748511/109782879-5922b800-7c44-11eb-85b0-c65bc30cc5c0.png)

**Comment by xueleilei120** [comment]
我的联系方式： qq 290484002

**Comment by lasting-yang** [comment]
不建议模拟器使用
