### ISSUE TITLE
hook_RegisterNatives Android11无法正常输出打印

### ISSUE THREAD

**Issue by HuRuWo** [lasting-yang/hook_art#7]
机型:pixle3
系统:安卓11
其他:安装面具已经获得root 安装LSposed

执行 `frida -U --no-pause -f com.ss.android.ugc.aweme -l hook_RegisterNatives.js`
只能打印两行注册地址:
```
RegisterNatives is at  ···
RegisterNatives is at  ···
```

切换到安卓8的手机之后恢复正常

**Comment by lasting-yang** [comment]
Android 11修复好了

**Comment by lasting-yang** [comment]
![image](https://user-images.githubusercontent.com/13957779/134441095-afbdcc7b-9591-4c90-ad13-6cec3ad8b419.png)
