### ISSUE TITLE
cannot read property 'base' of null

### ISSUE THREAD

**Issue by theBoy215** [lasting-yang/hook_art#9]
[RegisterNatives] method_count: 0x1
TypeError: cannot read property 'base' of null
    at onEnter (/hook_RegisterNatives.js:42)
[RegisterNatives] method_count: 0xc
[RegisterNatives] method_count: 0x9
TypeError: cannot read property 'base' of null
    at onEnter (/hook_RegisterNatives.js:42)
TypeError: cannot read property 'base' of null
    at onEnter (/hook_RegisterNatives.js:42)

这个错误是因为模拟器导致的吗？

**Comment by lasting-yang** [comment]
不建议使用模拟器, 最好是使用真机
